### ISSUE TITLE
Pass when given code from stdin

### ISSUE THREAD

**Issue by keithamus** [selaux/eslint-plugin-filenames#1]
I'm using this plugin with eslint - occasionally I need to use eslint in stdin mode (for example, the sublime plugin does this) - but this plugin fails because stdin sets the filename to `<text>`.

```bash
cat index.js | eslint --stdin

<text>
  1:0  error  Filename '<text>' does not match the naming convention  filenames/filenames

✖ 1 problem (1 error, 0 warnings)
```

The workaround for now is to amend the regexp to include `<text>` as a literal, e.g. 
```js
/^(<text>$|([a-z0-9]+)([A-Z][a-z0-9]+)*$)/
```

Ultimately it would be great if this plugin could properly detect that the input is coming from stdin and pass.

**Comment by selaux** [comment]
Can you test wether current master works for you? I will publish a new version on npm after.

**Comment by keithamus** [comment]
Works great for me :smile:
