### ISSUE TITLE
Support for JSX

### ISSUE THREAD

**Issue by dentuzhik** [selaux/eslint-plugin-filenames#10]
It would be useful, to check JSX components using this plugin. I tried to find something similar in [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react), no luck.

**Comment by selaux** [comment]
What is the result of linting JSX files with `eslint-plugin-filenames`? Isn't this possible (the extension shouldn't matter)?

**Comment by dentuzhik** [comment]
I have tried to create a failure in one of my JSX components for the `filenames/match-exported` rule, and no failure was reported. Plus the README clearly states, that only `.js` files are supported.
https://github.com/selaux/eslint-plugin-filenames/blame/master/README.md#L10

**Comment by selaux** [comment]
Hm, I created some test cases for JSX in #12 and it should work just fine. JSX is a feature of the parser used by eslint, so as long as it can be parsed it can be linted by this plugin. Can it be some other issue? E.g. is the export a default export?

**Comment by selaux** [comment]
Works?

**Comment by dentuzhik** [comment]
Yes, it does work, sorry for troubles. 👍 for tests. Does it make sense to change description in the README though?
