### ISSUE TITLE
Option to ignore certain paths

### ISSUE THREAD

**Issue by dentuzhik** [selaux/eslint-plugin-filenames#11]
Would be great to be able validation on certain paths, but still being able to lint them using all other eslint rules.

**Comment by selaux** [comment]
Doesn't adding a eslintrc that disables the rule to a directory work?

**Comment by dentuzhik** [comment]
Probably I don't get an idea, can you provide a draft of example?

**Comment by selaux** [comment]
Put a `.eslintrc` file into the directory where you want do disable the rule with the following content:

```
{
  "rules": {
    "filenames/match-exported": 0
  }
}
```

**Comment by selaux** [comment]
Works?

**Comment by dentuzhik** [comment]
Sorry, didn't have much time to check.
Yes, it does work, however ignoring files matching globs is impossible. 
I think it relates to the eslint itself, rather to the plugin (found [this](https://github.com/eslint/eslint/issues/3611)), so feel free to close the issue.

**Comment by selaux** [comment]
Yes, otherwise every rule would have to implement that for itself.
