### ISSUE TITLE
Test files (MyCalculator.test.js) are not allowed 

### ISSUE THREAD

**Issue by Ronsho** [selaux/eslint-plugin-filenames#25]
Hey all,
Great plugin, thanks for the work!
I am using Jest to write unit tests for a class in Node.js. Was wondering how to make the linter to allow this kind of file names.

**Comment by selaux** [comment]
Hi,

the solution is to adapt your regex for filenames as explained [here](https://github.com/selaux/eslint-plugin-filenames#consistent-filenames-via-regex-match-regex).
