### ISSUE TITLE
Add a flag to match the default exported name

### ISSUE THREAD

**Issue by BenoitZugmeyer** [selaux/eslint-plugin-filenames#3]
I would love to use this plugin with an additional flag, something like `"match-exported"`, to force the file name to be the same as the exported object. Here is an example:

```js
// The file has to be named File.js
export default class File {
}
```

```js
// The file has to be named makeTemporary.js
export default function makeTemporary() {
}
```

```js
// The file has to be named makeTemporary.js
module.exports = function makeTemporary() {
};
```

```js
// The file has to be named makeTemporary.js
module.exports = makeTemporary;
```

If the file does not export a default named object, it the file name should follow the regexp pattern.

```js
// The file name should follow the pattern passed as option
export class File {
}
```

```js
// The file name should follow the pattern passed as option
exports.File = File;
```

```js
// The file name should follow the pattern passed as option
export default {
  foo: "bar",
}
```

```js
// The file name should follow the pattern passed as option
export default class {
}
```

What do you think about it? I could make a PR for you if you are interested.

**Comment by selaux** [comment]
Sounds like a good idea, although I think that it should be a separate rule and not interfere with the regex matching rule. Would this be a problem for you use-case?

A PR would be very appreciated :+1:

**Comment by BenoitZugmeyer** [comment]
We could do a separate rule, but we still need a regexp to validate files that don't export default, named objects.

**Comment by selaux** [comment]
We could use an option to define a fallback regex.

**Comment by BenoitZugmeyer** [comment]
I don't understand: my point was simply to add an flag to the existing rule, so we can't have conflicting rules or regexes. The only regexp involved is the one existing right now. The flag only means: "if the file is exporting a default, don't use the regexp, the file has to be named like the exported value".

Usage example:
```js
filenames/filenames: [1, "^([A-Z][a-z0-9])+$", "match-exported"]
```

If we create two rules, those rules will conflict if they are used together:
```js
filenames/filenames: [1, "^([A-Z][a-z0-9])+$"]
filenames/match-exported: 1
// If a file is exporting the function makeTemporary, the first rule will enforce
// the name to start with an uppercase, but the second will enforce the name
// to be makeTemporary
```

Anyway, if you prefer two rules I'm ok with this, I don't have hard feelings about it!

I did start to work on it, I will make a PR soon, you'll let me know :)

**Comment by selaux** [comment]
To make the single rule, we need to specify several option-values to make it configurable for all cases.

Something like ```match-exported-or-regex``` (test export matching first, then fallback to regex, which would be you use case), ```match-regex-or-exported``` (test match for regex then fallback to export matching) and ```match-exported``` (which would require both to match).
