### ISSUE TITLE
Disallow file names ending with pattern

### ISSUE THREAD

**Issue by adamgajzlerowicz** [selaux/eslint-plugin-filenames#35]
How can I disallow particular file names?

For example if someone calls a file `MyClassStyle`, it would fail because the file ends with `Style`. In other words - no file should end with Style.

Is it possible to do it with this plugin? 

Thank you!

**Comment by Hotell** [comment]
It's not possible

see https://github.com/selaux/eslint-plugin-filenames/issues/39
